export enum ActionTypes {
    TASK_GET = 'TASK_GET',
    TASK_FETCH = 'TASK_FETCH',
    TASK_INCLUDE = 'TASK_INCLUDE',
    TASK_DELETE = 'TASK_DELETE',
    TASK_UPDATE = 'TASK_UPDATE',
    TASK_DONE = 'TASK_DONE',
    TASK_CHANGE_POSITION = 'TASK_CHANGE_POSITION'
}
