export enum ActionTypes {
    TASK_GET = 'TASK_GET',    
    TASK_INCLUDE = 'TASK_INCLUDE',
    TASK_DELETE = 'TASK_DELETE',
    TASK_UPDATE = 'TASK_UPDATE',
    TASK_DONE = 'TASK_DONE',
    TASK_CHANGE_POSITION = 'TASK_CHANGE_POSITION',
    TASK_FETCH_ERROR = 'TASK_FETCH_ERROR',
    TASK_FETCH_SUCCESS = 'TASK_FETCH_SUCCESS',
    TASK_FETCH_LOADING = 'TASK_FETCH_LOADING',
}
